tasks:
  - name: dev server
    command:  docker run --rm \
      --volume="$PWD:/srv/jekyll" \
      --publish 4000:4000 \
      jekyll/jekyll \
      jekyll serve
ports:
  - port: 4000
    onOpen: open-preview