image:
  file: .gitpod.Dockerfile

tasks:
  - name: dev server
    init:  gem install bundler &&
      bundle install
    command: bundle exec jekyll serve
ports:
  - port: 4000
    onOpen: open-preview