tasks:
  - name: dev server
    init: 
      rvm install 2.7.2 && 
      rvm use 2.7.2 &&
      gem install bundler &&
      bundle install --jobs=4
    command: bundle exec jekyll serve
ports:
  - port: 4000
    onOpen: open-preview

vscode:
  workbench:
    startupEditor: readme